### ISSUE TITLE
README is missing link to hosted version and install instructions

### ISSUE THREAD

**Issue by machinekoder** [twhite96/checkyoself#303]
Reading through the README and the docs its hard to find out how to try out checkyoself.

**Comment by twhite96** [comment]
Thanks for commenting on this. It could definitely be clearer. It's still very much a WIP. I've written the text component several times. I'll keep this open to think about improving the README and docs. You should check out the [blog](https://checkyoself-docs.netlify.com/blog/) for further updates on this. It's just a side project for now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Zenchiyu** [comment]
Hello,
The link to your blog is broken, can you provide a new link? Thank you!

Regards,
Stéphane

**Comment by twhite96** [comment]
@Zenchiyu hey sorry, but I've abandoned this project. I am no longer working on this so if you'd like to fork it or whatever go ahead. I let the domain expire. Sorry about that.
